## vector or matrix transpose

use T method

In [15]:
import numpy as np

# 행렬 만들고 전치한다
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(matrix.T)

# transpose method사용해도 가능
print(matrix.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
# transpose method 사용, 튜플로 바꿀차원 직접 지정가능
# 2*3*2행렬 만든다
matrix_2 = np.array([[[1, 2],
                     [3, 4],
                     [5, 6]],
                    
                    [[7, 8],
                    [9, 10],
                    [11, 12]]])
print(matrix_2)
print('\n')

# change 2nd, 3rd into 2*2*3 행렬 만든다
print(matrix_2.transpose((0, 2, 1)))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


[[[ 1  3  5]
  [ 2  4  6]]

 [[ 7  9 11]
  [ 8 10 12]]]


In [5]:
# 벡터 전치는 선형대수와 달리 불가, 단지 행벡터를 열벡터로 변환 혹은 그 반대 가능하다. 대괄호 두번 사용해서 해결한다
vector_1 = np.array([1, 2, 3, 4, 5, 6])
print(vector_1.T)

vector_2 = np.array([[1, 2, 3, 4, 5, 6]])
print(vector_2.T)

vector_3 = np.array([vector_1])
print(vector_3)
print(vector_3.T)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## 행렬 펼치기

### 행렬을 1차원 배열로

flatten method 사용한다

In [11]:
print(matrix)

print(matrix.flatten())  # 새로운 배열을 만든다

# 혹은 reshape method, 넘파이 배열의 view를 반환
print(matrix.reshape(1, -1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


In [16]:
vector_flattened = matrix.flatten()
vector_reshaped = matrix.reshape(-1)

# change (0, 0) element
matrix[0][0] = -1

# reshape method는 원본의 변경이 반영됨, 복사이므로.
print(vector_reshaped)
print('\n')

# flatten method는 새 배열이므로 변경된 원본과 같지 않음
print(vector_flattened)

[-1  2  3  4  5  6  7  8  9]


[1 2 3 4 5 6 7 8 9]


In [2]:
# rank
import numpy as np
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])
np.linalg.matrix_rank(matrix)

2

### calculate determinant

numpy method det 사용한다

In [3]:
print(matrix)

np.linalg.det(matrix)

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


0.0

In [4]:
# 대각원소 추출하기
print(matrix)
matrix.diagonal()

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


array([ 1,  1, 15])

In [9]:
# 주대각선 하나위의 대각원소 반환하기
print(matrix.diagonal(offset=1))

# 그의 합 반환하기
print(matrix.trace(offset=1))

[ 1 10]
11


In [8]:
# 대각합계산
print(matrix)

print(matrix.trace())

# 동일한 계산 결과
print(sum(matrix.diagonal()))

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]
17
17


In [12]:
# dot product
import numpy as np

va = np.array([1,2,3])
vb = np.array([4,5,6])

print(np.dot(va, vb))
print(va@vb)

32
32


In [15]:
# matrix add, subtract
ma = np.array([[1,2,3],
              [1,1,1],
              [1,1,2]])
mb = np.array([[1,3,1],
              [1,3,1],
              [1,3,8]])
print(np.add(ma,mb))
print(ma+mb)
print(np.subtract(ma,mb))
print(ma-mb)

[[ 2  5  4]
 [ 2  4  2]
 [ 2  4 10]]
[[ 2  5  4]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -1  2]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 0 -1  2]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [16]:
print(ma*mb)
print(ma@mb)

[[ 1  6  3]
 [ 1  3  1]
 [ 1  3 16]]
[[ 6 18 27]
 [ 3  9 10]
 [ 4 12 18]]


In [17]:
# dot product 다차원 배열도 가능, 단 (a,b,c,D)크기 배열과 (e,f,D,h) 크기 배열 내적시
# (a,b,c,e,f,h) 크기 반환

In [21]:
print(ma)

# 역행렬
inva = np.linalg.inv(ma)
print(inva)
print(ma@inva)
print(np.matmul(ma,inva))

[[1 2 3]
 [1 1 1]
 [1 1 2]]
[[-1.  1.  1.]
 [ 1.  1. -2.]
 [ 0. -1.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### generate random number

In [22]:
# 초기값지정
np.random.seed(0)

# 0, 1사이 세개 실수 생성
print(np.random.random(3))

[0.5488135  0.71518937 0.60276338]


In [28]:
# 0, 10사이 정수 세개 생성, 0포함 11포함안함
np.random.randint(0, 11, 3)

array([4, 3, 0])

In [35]:
# 평균0, 표준편차1인 정규분포에서 세개 생성
print(np.random.normal(0, 1, 3),'\n')

# 평균0, 스케일1인 로지스틱 분포에서 세개 추출
print(np.random.logistic(0,1 ,3),'\n')

print(np.random.uniform(0, 1, 3),'\n')

# np.random.normal(0, 1, (2, 3))과 동일
print(np.random.standard_normal((2,3)), '\n')

print(np.random.randn(2,3))

[ 0.93755884 -0.25460809  0.97359871] 

[0.8119815  0.97067631 0.00529754] 

[0.95608363 0.6439902  0.42385505] 

[[ 0.20728277 -0.24107359  0.05334491]
 [ 1.03081595 -1.27698899  0.83771977]] 

[[-1.49011141 -1.070215   -0.20912862]
 [ 0.60457228 -1.74305823  1.52422681]]


In [37]:
print(np.random.choice([0,1,200],5))

[200   0 200 200 200]


In [41]:
a = np.array([0,1,2,3,4])
np.random.shuffle(a)
a

array([1, 2, 0, 3, 4])

In [40]:
a

array([0, 3, 1, 4, 2])

In [42]:
np.random.permutation(a)

array([1, 0, 2, 4, 3])

In [43]:
a

array([1, 2, 0, 3, 4])

In [44]:
np.random.permutation(15)

array([11,  0, 12,  2,  9,  6,  8,  1,  7, 10, 13, 14,  4,  3,  5])